import sqlite3

con = sqlite3.connect("easyjob.db")
c = con.cursor()

questions = [

# ================= LOGICAL (25) =================
("logical","Series: 3, 9, 27, 81, ?","162","243","324","729","b"),
("logical","Find missing: 2, 6, 12, 20, ?","28","30","32","36","a"),
("logical","If CAT = 24, DOG = ?","26","28","30","32","c"),
("logical","Clock angle at 4:40","100","110","120","130","b"),
("logical","If 1=3, 2=6, 3=11, 4=?","14","15","16","17","b"),
("logical","Mirror of 3:35","8:25","8:20","9:25","9:20","a"),
("logical","Next: AZ, BY, CX, ?","DW","EV","DU","EW","a"),
("logical","A man walks 10km N, 5km E, 10km S. Distance?","0","5","10","15","b"),
("logical","Odd one: Iron, Copper, Gold, Plastic","Iron","Copper","Gold","Plastic","d"),
("logical","If MON = 36, SUN = ?","52","54","56","58","b"),
("logical","Find missing: 1, 4, 9, 16, ?","20","24","25","30","c"),
("logical","Series: 2, 5, 10, 17, ?","24","25","26","27","c"),
("logical","If A=1, Z=26, then CAT = ?","22","24","26","27","b"),
("logical","Odd: Square, Rectangle, Circle, Triangle","Square","Rectangle","Circle","Triangle","c"),
("logical","Mirror of 7:20","4:40","4:30","5:40","5:30","a"),
("logical","Series: 5, 10, 20, 40, ?","60","70","80","90","c"),
("logical","If today is Monday, after 61 days?","Monday","Tuesday","Wednesday","Thursday","c"),
("logical","Next: B, E, H, K, ?","L","M","N","O","b"),
("logical","Find odd: Apple, Mango, Carrot, Banana","Apple","Mango","Carrot","Banana","c"),
("logical","Series: 100, 90, 80, ?","60","70","75","85","b"),
("logical","If 3 pens cost 15, 9 pens cost?","30","35","40","45","d"),
("logical","Next: 1, 3, 6, 10, ?","12","13","14","15","d"),
("logical","Odd: CPU, RAM, ROM, Mouse","CPU","RAM","ROM","Mouse","d"),
("logical","Series: 7, 14, 28, ?","42","49","56","64","c"),
("logical","If ALL = 36, EGG = ?","18","21","24","27","c"),

# ================= MATH (25) =================
("math","If x+5 = 2x-3, find x","6","7","8","9","b"),
("math","Train 150m passes pole in 15 sec, speed?","30 km/h","36 km/h","40 km/h","45 km/h","b"),
("math","LCM of 12,18,24","48","72","36","60","b"),
("math","Simple Interest on 5000 at 10% for 2 years","900","1000","1100","1200","b"),
("math","20% of x = 80, x = ?","300","350","400","450","c"),
("math","Area of circle radius 7","44","154","132","100","b"),
("math","If CP=100, SP=120, profit %","15%","18%","20%","25%","c"),
("math","Sum of first 10 natural numbers","45","50","55","60","c"),
("math","Time: A does work in 10 days, B in 20 days","5","6.7","7","8","b"),
("math","Average of 2,4,6,8","4","5","6","7","b"),
("math","Square root of 144","10","11","12","13","c"),
("math","5^3","75","100","125","150","c"),
("math","Value of pi","3.12","3.14","3.16","3.18","b"),
("math","HCF of 24,36","6","8","12","18","c"),
("math","30% of 200","40","50","60","70","c"),
("math","Distance = speed × ?","Time","Work","Power","Force","a"),
("math","Perimeter of square side 6","20","22","24","26","c"),
("math","10^3","100","500","1000","2000","c"),
("math","2+2*3","8","10","6","12","a"),
("math","Cube of 4","16","32","48","64","d"),
("math","1 km = ? m","100","500","1000","1500","c"),
("math","50% of 80","30","35","40","45","c"),
("math","Simple interest formula","PRT","PTR","RPT","TPR","a"),
("math","Prime number","9","11","15","21","b"),
("math","Odd number","12","14","17","18","c"),

# ================= ENGLISH (25) =================
("english","Synonym of Meticulous","Careless","Detailed","Lazy","Fast","b"),
("english","Antonym of Reluctant","Eager","Slow","Weak","Lazy","a"),
("english","Meaning of Ubiquitous","Rare","Everywhere","Unknown","Dangerous","b"),
("english","Correct: Neither of the boys ___ guilty","are","were","is","have","c"),
("english","Passive: She wrote a letter","is written","was written","had written","is being written","b"),
("english","One word: fear of heights","Acrophobia","Hydrophobia","Claustrophobia","Agoraphobia","a"),
("english","Synonym of Obsolete","Modern","Outdated","New","Fresh","b"),
("english","Fill: Hardly ___ finished when rain started","I had","I have","I was","I am","a"),
("english","Correct spelling","Entreprenuer","Entrepreneur","Enterprenaur","Enterpreneur","b"),
("english","Synonym of Pragmatic","Idealistic","Practical","Lazy","Careless","b"),
("english","Antonym of Transparent","Clear","Hidden","Visible","Bright","b"),
("english","Meaning of Candid","Honest","Angry","Lazy","Silent","a"),
("english","Fill: He has been ___ since morning","sleep","slept","sleeping","asleep","c"),
("english","Synonym of Abundant","Rare","Plenty","Few","None","b"),
("english","Correct: Each of the students ___ present","are","were","is","have","c"),
("english","Antonym of Fragile","Weak","Delicate","Strong","Soft","c"),
("english","Meaning of Inevitable","Avoidable","Certain","Rare","Hidden","b"),
("english","Synonym of Diligent","Lazy","Hardworking","Slow","Weak","b"),
("english","Fill: I look forward to ___ you","meet","meeting","met","meets","b"),
("english","Correct: She prefers tea ___ coffee","than","over","to","from","c"),
("english","Synonym of Eloquent","Silent","Fluent","Angry","Weak","b"),
("english","Antonym of Expand","Grow","Increase","Shrink","Open","c"),
("english","Meaning of Scarce","Plenty","Rare","Easy","Cheap","b"),
("english","Correct: He is good ___ maths","in","at","on","for","b"),
("english","Synonym of Hostile","Friendly","Aggressive","Kind","Calm","b"),

# ================= GK (25) =================
("gk","Theory of relativity by","Newton","Einstein","Galileo","Tesla","b"),
("gk","Greenhouse gas","Oxygen","Nitrogen","CO2","Hydrogen","c"),
("gk","Longest dam in India","Bhakra","Hirakud","Tehri","Sardar","b"),
("gk","WHO HQ","NY","Paris","Geneva","Rome","c"),
("gk","First Indian Nobel","Tagore","CV Raman","Mother Teresa","Amartya Sen","a"),
("gk","Largest organ in human body","Heart","Skin","Liver","Brain","b"),
("gk","Currency of China","Yen","Won","Yuan","Dollar","c"),
("gk","Father of Computer","Newton","Einstein","Babbage","Tesla","c"),
("gk","Fastest bird","Eagle","Falcon","Crow","Sparrow","b"),
("gk","Largest planet","Earth","Mars","Jupiter","Saturn","c"),
("gk","Chemical symbol of gold","Ag","Au","Fe","Pb","b"),
("gk","National flower of India","Rose","Lotus","Lily","Sunflower","b"),
("gk","Smallest bone","Femur","Stapes","Tibia","Radius","b"),
("gk","Red planet","Earth","Mars","Jupiter","Venus","b"),
("gk","First PM of India","Patel","Nehru","Gandhi","Bose","b"),
("gk","Full form of RAM","Random Access Memory","Read Access Memory","Rapid Access Memory","None","a"),
("gk","Largest ocean","Atlantic","Indian","Pacific","Arctic","c"),
("gk","Gas in photosynthesis","Oxygen","Nitrogen","Carbon dioxide","Hydrogen","c"),
("gk","Author of Harry Potter","Tolkien","Rowling","Martin","Lewis","b"),
("gk","Longest river","Amazon","Nile","Yangtze","Ganga","b"),
("gk","National animal","Lion","Tiger","Elephant","Horse","b"),
("gk","First man on moon","Armstrong","Aldrin","Collins","Gagarin","a"),
("gk","India independence year","1945","1946","1947","1948","c"),
("gk","Blood group universal donor","A","B","AB","O","d"),
("gk","Light year measures","Time","Speed","Distance","Energy","c"),

# ================= C (25) =================
("c","Highest precedence","++","*","+","=","a"),
("c","Dynamic memory","malloc","scanf","printf","sizeof","a"),
("c","sizeof(float)","2","4","8","16","b"),
("c","Dangling pointer","Null","Unused","Freed memory","Syntax error","c"),
("c","Correct pointer","int *p","int p*","int &p","pointer p","a"),
("c","Not storage class","auto","static","volatile","register","c"),
("c","File pointer type","int","FILE","char","void","b"),
("c","Recursion needs","Loop","Call","Base condition","Pointer","c"),
("c","Which returns address","scanf","printf","malloc","sizeof","c"),
("c","Not keyword","struct","union","class","enum","c"),
("c","String ends with","\\n","\\0","space","EOF","b"),
("c","Array starts index","0","1","-1","Depends","a"),
("c","Logical AND","&&","||","&","|","a"),
("c","Header for printf","stdio.h","conio.h","math.h","stdlib.h","a"),
("c","Which is loop","if","for","switch","break","b"),
("c","Escape new line","\\t","\\n","\\b","\\a","b"),
("c","Data type for decimal","int","char","float","void","c"),
("c","Constant define","#define","const","static","macro","a"),
("c","Which is IDE","VS Code","MS Word","Excel","Chrome","a"),
("c","Compiler","GCC","Chrome","Excel","Notepad","a"),
("c","Ends statement",";"," :",",","|","a"),
("c","Symbol for address","*","&","%","#","b"),
("c","Which prints","scanf","printf","input","print","b"),
("c","Which is comment","// hi","/* hi */","both","none","c"),
("c","Main function","main()","start()","run()","begin()","a")

]


for q in questions:
    c.execute("INSERT INTO questions VALUES(NULL,?,?,?,?,?,?,?)", q)

con.commit()
print("All 125 questions inserted successfully")
